### ISSUE TITLE
could you add a direct link to the website in the repository description?

### ISSUE THREAD

**Issue by robertoostenveld** [ohbm/osr2021#4]
i.e. at the top of the column on the right, just under "About". 

This is the link from last year:

<img width="586" alt="Screenshot 2021-06-11 at 16 20 19" src="https://user-images.githubusercontent.com/899043/121701249-feb1b700-cad0-11eb-82a6-13dc4c780274.png">

**Comment by GGonEsc** [comment]
Done!
