### ISSUE TITLE
OpenNeuro's new PET Projects: State of BIDS PET (Emergent session, osr abstract submission)

### ISSUE THREAD

**Issue by bendhouseart** [ohbm/osr2021#5]
# OpenNeuro's new PET Projects: State of BIDS PET

*By Anthony Galassi et al, OpenNeuro* 

- Theme: Current state of PET BIDS and related efforts/projects
- Format: Emergent session

## Abstract

PET imaging has recently been added to the BIDS standard and this emergent session would serve to inform attendees of the previous work as well as much of the ongoing efforts to integrate PET data into BIDS. This session is aimed at anyone who is currently working in PET neuroimaging, is curious about how the addition of PET data might be added to their own research, or is a general enthusiast of BIDS.

This session will include a brief discussion about the recent addition of PET to BIDS and highlight some of the efforts surrounding/following this addition such as:

- The inclusion of PET data into OpenNeuro
- Adding  support for BIDS PET/PET Imaging to popular Neuroscience libraries/toolsets     
- The challenges of dealing with PET datasets and their many incongruities e.g. proprietary file formats, non-uniform metadata, existing methods and solutions to some of those issues (some of which are included below in the useful links section)

## Useful Links
[BIDS extension proposal 009](https://github.com/bids-standard/bids-specification/pull/633)

[BIDS PET doc](https://bids-specification.readthedocs.io/en/stable/04-modality-specific-files/09-positron-emission-tomography.html)

[BIDS Starter Kit](https://github.com/bids-standard/bids-starter-kit/)
- [Creating a BIDS compatible PET dataset](https://github.com/bids-standard/bids-starter-kit/wiki/Creating-a-BIDS-compatible-PET-dataset)
- [Building required BIDS metadata text files from a PET dataset](https://github.com/CPernet/bids-starter-kit/tree/main/matlabCode)

[Matlab BIDS Converter](https://github.com/openneuropet/BIDS-converter)

**Comment by evaalonsoortiz** [comment]
@bendhouseart Hi! This year emergent session requests will be made through the OSR website (https://ohbm.github.io/osr2021/submit/) during the week of the OSR only. Applications for sessions will be given a time slot on a first-come first-serve basis. Thank you!

**Comment by bendhouseart** [comment]
Ok gotcha, thank you.
